### PR TITLE
Avoid using EXECUTABLE as global variable

### PR DESCRIPTION
**Pull request by AbcSxyZ**
Naming changes. It was using `EXECUTABLE` variable globally to access to the used executable. Avoid to do that, passing the variable as function argument, looks cleaner.

### CODE REVIEW

**Review by patricklodder — DISMISSED** [review]
tested ACK

**Comment by patricklodder** [comment]
@AbcSxyZ could you give this one a rebase? I tested it, but #10 messed up the integration of this.

**Comment by AbcSxyZ** [comment]
Rebase done.

**Review by patricklodder — APPROVED** [review]
tested ACK.

**Pull request merged**
