### PR TITLE
deps/apt-get

### PR DESCRIPTION
**Pull request by xanimo**
fix [DL3027](https://github.com/hadolint/hadolint/wiki/DL3027)

### CODE REVIEW

**Review by AbcSxyZ — DISMISSED** [review]
ACK. We can add hadolint linter too, I will recommend it in https://github.com/dogecoin/docker/pull/37.

**Comment by patricklodder** [comment]
Needs rebase

**Comment by xanimo** [comment]
> Needs rebase

done

**Review by patricklodder — APPROVED** [review]
tested ACK. Thanks!

**Pull request merged**
