### PR TITLE
qa: pick a js standard and just comply

### PR DESCRIPTION
**Pull request by patricklodder**
Easier to just comply to a standard and make it all awesome.

Standard: semistandard - because without semicolons function piping becomes hard to decipher. 

Changes made to comply with the standard:
  - remove trailing comma
  - space between class method name and input signature
  - no block padding
  - no multi-space to align comments
  - semicolons everywhere

### CODE REVIEW

**Review by AbcSxyZ — APPROVED** [review]
ACK. I was wondering if GA was using pushed code, it was interesting to notice it is using workflow & genmatrix.js of the PR.

You will have a linter to add later ?

**Comment by patricklodder** [comment]
> You will have a linter to add later ?

I have linters ready for both py and js, am still figuring out hadolint

**Review by xanimo — APPROVED** [review]
ACK. however with regards to semi-colons everywhere, is this not applicable to classes?

**Comment by patricklodder** [comment]
>  is this not applicable to classes?

not `class {}` and not `function {}` because those are declarations, also not things like blocks `if (test) { }`. But `const a = function(){};` is an expression so there yes.

**Pull request merged**
