### PR TITLE
Create main function in entrypoint + rename entrypoint

### PR DESCRIPTION
**Pull request by AbcSxyZ**
Create a main function to call in entrypoint + rename `docker-entrypoint.py`

Facilitate import of entrypoint for test coverage in https://github.com/dogecoin/docker/pull/25.

### CODE REVIEW

**Comment by patricklodder** [comment]
I was just working on [fixing python lint suggestions](https://github.com/patricklodder/docker-dogecoin/commit/8afe8dd5e903182f331e7bcba561e34e4d186d9a) and these were findings there... I'll rebase mine on top of yours.

**Review by patricklodder — DISMISSED** [review]
ACK - code reviewed & tested to work on x86_64

**Review by patricklodder — CHANGES_REQUESTED** [review]
When rebasing my lint fixes on top of this, I found that the second commit overwrites the first commit's changes.

**Comment by AbcSxyZ** [comment]
Yep, commit troubles... Fixed.

**Review by patricklodder — APPROVED** [review]
ACK - code reviewed and tested on x86_64, again 😁

**Review by xanimo — APPROVED** [review]
ACK also tested on amd64

**Pull request merged**
